# Site settings
title: Sittercity Tech
description: > # this means to ignore newlines until "baseurl:"
  Learn all about all of the interesting stuff going on at Sittercity
  Tech! Well, interesting if you are a total dork, I guess.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost" # the base hostname & protocol for your site
host: 0.0.0.0
twitter_username: sittercitytech
github_username:  sittercity
port: 8080

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Build settings
markdown: kramdown

permalink: "/:title" # only make routes

paginate: 5
paginate_path: "/page/:num/"

authors:
  Phil Trimble:
    github: ptrimble
  Bob Vonderau:
    github: ravenduo
  Kelsey Mok:
    github: kelseymok
  Jazmin Schroeder:
    github: jazminschroeder
  Ryan Messner:
    github: rpmessner
  Sam De Freyssinet:
    github: samsoir
  Shane Gibbs:
    github: shanegibbs
  Jeremy Bush:
    github: zombor
  Edwin Mourant:
    github: emourant
  Ben Downey:
    github: bnd5k
  Jonathan Fantham:
    github: jonathan-fantham
  Chris Bandy:
    github: cbandy
  Eleanor Lee:
    github: ellie007
